server:
  port: 9005

spring:
  datasource:
    url: jdbc:mysql://localhost/hospital?useSSL=false
    username: patient
    password: serife

  jpa:
    hibernate:
      ddl-auto: update

medical:
  prices:
    chemotherapy : 5000
    operation: 3000
    naproxen: 8
    gaviscon: 10
