spring:
  data:
    mongodb:
      uri: mongodb://localhost/patients
server:
  port: 9004

pharmacy:
  medicines:
    migren: naproxen
    reflux: gaviscon

accountancy:
  url: http://localhost:9005/patients