server:
  port: 8001


management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  datasource:
    url: jdbc:mysql://localhost/coding_cafe?useSSL=false
    username: cashier
    password: cashier

  jpa:
    hibernate:
      ddl-auto: update

feign:
  client:
    config:
      default:
        connectTimeout: 20000
        readTimeout: 20000